version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: ["start-dev", "--import-realm", "--hostname-strict=false"]
    environment:
      # Banco em memória só para dev
      KC_DB: dev-mem
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      # Monte uma PASTA com os json/yaml do(s) realm(s)
      - ./keycloak/import:/opt/keycloak/data/import
    ports:
      - "8081:8080"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: escola
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d escola"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/escola
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/realms/unifor
      # se precisar: QUARKUS_OIDC_CLIENT_ID=quarkus-api
    depends_on:
      - db
      - keycloak
    ports:
      - "8080:8080"
